name: Trigger auto deployment for cloud-a2-flask

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cloud-a2-flask-AutoDeployTrigger-339779ae-ae92-4542-a4c0-31e2276c7b42.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLOUDA2FLASK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLOUDA2FLASK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLOUDA2FLASK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: registrya2.azurecr.io
          registryUsername: ${{ secrets.CLOUDA2FLASK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLOUDA2FLASK_REGISTRY_PASSWORD }}
          containerAppName: cloud-a2-flask
          resourceGroup: cloud-a2
          imageToBuild: registrya2.azurecr.io/cloud-a2-flask:${{ github.sha }}
          


